### ISSUE TITLE
Akamai_Sensor_Generator code running problem

### ISSUE THREAD

**Issue by yoyoyo12321** [HypePhilosophy/Akamai_Sensor_Generator#5]
When I ran the code, I found that browserData was commented out and caused an error, but the corresponding data.json was not found in the github link. I guess you forgot to upload the file data.json.
I would appreciate that if you can help me with the problem.

**Comment by yoyoyo12321** [comment]
> When I ran the code, I found that browserData was commented out and caused an error, but the corresponding data.json was not found in the github link. I guess you forgot to upload the file data.json.
> I would appreciate that if you can help me with the problem.
![image](https://user-images.githubusercontent.com/78837044/107869287-70814780-6ec7-11eb-8a7d-35cc87102109.png)

**Comment by HypePhilosophy** [comment]
Hi @yoyoyo12321, unfortunately, I do not plan on adding in the data.json file as that was harvested with user permission. However, they did not give permission for it to be open-sourced so I cannot release it. I recommend you remove any instance of dataNum and browserData instead. If I remember correctly, those variables are only used when referencing akamai canvas data that needs to be harvested. If you cannot harvest the canvas data, a random string will suffice for limited testing.
